name: Terraform Plan

on:
  push:
    #paths:
      #- 'terraform/**' # Trigger only if something changes in the 'terraform' directory
    branches:
      - master 
jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Change directory to Terraform directory
      run: cd terraform
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
      
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      id: plan
      
    - name: Save plan artifact
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: ./tfplan
