name: Docker Build and Push

on:
  push:
    branches:
      - master 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Run Unit Tests
      run: |
        export JWT_SECRET=secret123
        docker build ./auth-service -t ${{secrets.DOCKER_USERNAME}}/auth-service:latest
        docker run ${{secrets.DOCKER_USERNAME}}/auth-service:latest npm test
      
    - name: Build and Push Docker Images
      run: |
        docker build ./auth-service -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
